# Generated by Django 5.2.14 on 2026-05-21 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ticket_created', 'Ticket Created'), ('ticket_status_changed', 'Ticket Status Changed'), ('ticket_assigned', 'Ticket Assigned'), ('task_created', 'Task Created'), ('task_assigned', 'Task Assigned'), ('ticket_converted', 'Ticket Converted to Task'), ('comment_added', 'Comment Added'), ('sla_breached', 'SLA Breached')], db_index=True, max_length=50)),
                ('target_type', models.CharField(db_index=True, help_text="e.g., 'ticket', 'task'", max_length=50)),
                ('target_id', models.IntegerField(db_index=True, help_text='ID of the affected object')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(help_text='The user who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='audit_logs_organiz_af0d8d_idx')],
            },
        ),
    ]
