# Generated by Django 5.2.14 on 2026-05-21 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('response_time_hours', models.FloatField(default=24.0, help_text='Time to first response in hours.')),
                ('resolution_time_hours', models.FloatField(default=48.0, help_text='Time to resolution in hours.')),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_configs', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'SLA Config',
                'verbose_name_plural': 'SLA Configs',
                'db_table': 'sla_configs',
                'indexes': [models.Index(fields=['organization', 'is_active'], name='sla_configs_organiz_55f64b_idx')],
                'unique_together': {('organization', 'priority')},
            },
        ),
    ]
